# Generated by Django 4.2.7 on 2023-11-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('course', models.CharField(max_length=120)),
                ('highestqualification', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Staf',
        ),
    ]
