# Generated by Django 4.2.7 on 2023-11-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0002_staf_delete_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=120)),
                ('Lastname', models.CharField(max_length=120)),
                ('Email', models.EmailField(max_length=50, unique=True)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Password', models.CharField(max_length=20)),
                ('Profile', models.ImageField(upload_to='')),
                ('Course', models.CharField(max_length=20)),
                ('Session', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=120)),
                ('Lastname', models.CharField(max_length=120)),
                ('Email', models.EmailField(max_length=50, unique=True)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Password', models.CharField(max_length=20)),
                ('Profile', models.ImageField(upload_to='')),
                ('Address', models.TextField()),
                ('Course', models.CharField(max_length=20)),
                ('Resume', models.FileField(upload_to='documents')),
            ],
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
