# Generated by Django 4.2.7 on 2023-11-30 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finalapp', '0013_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherleave',
            name='user',
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
