# Generated by Django 4.2.7 on 2023-11-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0014_remove_teacherleave_user_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfeedback',
            name='is_reviewed',
        ),
        migrations.RemoveField(
            model_name='studentfeedback',
            name='review_text',
        ),
        migrations.RemoveField(
            model_name='studentform',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='studentform',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='teacherfeedback',
            name='is_reviewed',
        ),
        migrations.RemoveField(
            model_name='teacherfeedback',
            name='review_text',
        ),
        migrations.AlterField(
            model_name='studentform',
            name='grade',
            field=models.CharField(max_length=10),
        ),
    ]
