# Generated by Django 4.2.7 on 2023-11-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0015_remove_studentfeedback_is_reviewed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentform',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentform',
            name='parent_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentform',
            name='grade',
            field=models.CharField(choices=[('1', '1st Grade'), ('2', '2nd Grade'), ('3', '3rd Grade'), ('4', '4th Grade'), ('5', '5th Grade')], max_length=10),
        ),
    ]
