# Generated by Django 4.2.7 on 2023-12-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0017_studentextra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentextra',
            name='user',
        ),
        migrations.AlterField(
            model_name='studentform',
            name='grade',
            field=models.CharField(choices=[('1', '1st Grade'), ('2', '2nd Grade'), ('3', '3rd Grade'), ('4', '4th Grade'), ('5', '5th Grade'), ('6', '6th Grade'), ('7', '7th Grade'), ('8', '8th Grade'), ('9', '9th Grade'), ('10', '10th Grade')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentform',
            name='parent_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='StudentExtra',
        ),
    ]
