# Generated by Django 4.2.7 on 2023-12-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0018_remove_studentextra_user_alter_studentform_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter', models.TextField()),
            ],
        ),
    ]
