# Generated by Django 4.2.7 on 2023-12-01 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0019_teacherjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Resume',
        ),
    ]
