# Generated by Django 4.2.7 on 2023-12-02 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0021_rename_email_teacherjob_enter_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherjob',
            old_name='upload_resume',
            new_name='resume',
        ),
    ]
