# Generated by Django 4.2.7 on 2023-12-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0023_rename_address_studentform_enter_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentform',
            old_name='select_gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='studentform',
            old_name='select_grade',
            new_name='grade',
        ),
        migrations.RemoveField(
            model_name='studentform',
            name='enter_address',
        ),
        migrations.AddField(
            model_name='studentform',
            name='address',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
    ]
