# Generated by Django 4.2.7 on 2023-12-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0024_rename_select_gender_studentform_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentform',
            name='address',
            field=models.TextField(max_length=200),
        ),
    ]
