# Generated by Django 4.2.7 on 2023-12-02 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0025_alter_studentform_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Course',
            new_name='Subject',
        ),
    ]
