# Generated by Django 4.2.7 on 2023-12-04 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0032_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='fee_id',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finalapp.fee')),
            ],
        ),
    ]
