# Generated by Django 4.2.7 on 2023-12-04 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0035_remove_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='finalapp.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentform',
            name='grade',
            field=models.CharField(choices=[('1', 'MSDS'), ('2', 'MSCS-A'), ('3', 'MSCS-B'), ('4', 'MECS'), ('5', 'MCCS'), ('6', 'MPCS'), ('7', 'BZC'), ('8', 'AZC'), ('9', 'FMB'), ('10', 'FMC'), ('11', 'Bcom'), ('12', 'BBA')], max_length=10),
        ),
    ]
