# Generated by Django 4.2.7 on 2023-12-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0037_remove_course_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses', to='finalapp.student'),
        ),
    ]
