# Generated by Django 4.2.7 on 2023-12-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0038_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
