# Generated by Django 5.0 on 2023-12-10 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0039_teacherjob_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
    ]
