# Generated by Django 5.0 on 2023-12-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0041_studentadmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Course',
            field=models.CharField(choices=[('1', 'MSDS'), ('2', 'MSCS-A'), ('3', 'MSCS-B'), ('4', 'MECS'), ('5', 'MCCS'), ('6', 'MPCS'), ('7', 'BZC'), ('8', 'AZC'), ('9', 'FMB'), ('10', 'FMC'), ('11', 'Bcom'), ('12', 'BBA')], max_length=10),
        ),
    ]
