# Generated by Django 5.0 on 2023-12-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0042_alter_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Course',
            field=models.CharField(choices=[('MSDS', 'MSDS'), ('MSCS-A', 'MSCS-A'), ('MSCS-B', 'MSCS-B'), ('MECS', 'MECS'), ('MCCS', 'MCCS'), ('MPCS', 'MPCS'), ('BZC', 'BZC'), ('AZC', 'AZC'), ('FMB', 'FMB'), ('FMC', 'FMC'), ('Bcom', 'Bcom'), ('BBA', 'BBA')], max_length=10),
        ),
    ]
