# Generated by Django 5.0 on 2023-12-12 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0043_alter_student_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='student',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Course',
            new_name='Co',
        ),
    ]
