# Generated by Django 5.0 on 2023-12-12 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0044_rename_student_attendance_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='course',
            new_name='Co',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='teacher',
        ),
    ]
