# Generated by Django 5.0 on 2023-12-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0045_rename_course_attendance_co_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='present_status',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
