# Generated by Django 5.0 on 2023-12-12 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0047_attendance_user_alter_attendance_co'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='user',
        ),
    ]
