# Generated by Django 5.0 on 2023-12-12 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0048_remove_attendance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='Co',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalapp.student'),
        ),
    ]
