# Generated by Django 5.0 on 2023-12-12 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0049_alter_attendance_co'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='Co',
            new_name='student',
        ),
    ]
