# Generated by Django 4.2.7 on 2023-12-15 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0051_attendance_co'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='co',
        ),
    ]
