# Generated by Django 4.2.7 on 2023-12-15 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0052_remove_attendance_co'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='end_date',
        ),
    ]
